#line 2 "lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 120
#define YY_END_OF_BUFFER 121
static yyconst short int yy_accept[319] =
    {   0,
        0,    0,    0,    0,  121,  115,  114,  113,   67,  115,
       89,   74,   44,  115,   82,   83,   72,   70,   88,   71,
       58,   73,  106,  106,   19,   43,   62,   59,   63,  105,
      105,  105,  105,  105,   84,   85,   75,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,   86,   93,
       87,   78,  116,  117,  116,  116,  114,   66,    0,  109,
        0,    0,    0,   80,    1,  112,   69,  110,  106,    0,
        0,   61,    0,   68,   76,   64,   79,   65,   77,  105,
      105,  105,  105,  105,    5,  102,  105,  105,  105,  105,

      105,  105,  105,  105,   35,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,   29,  105,  105,  105,
      105,  105,  105,   94,  105,    3,  105,   90,  105,  105,
      105,  105,   92,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,   11,  119,    0,  109,
        0,    0,  111,  111,  110,  107,    0,  108,   81,   60,
        4,  105,  105,   17,    2,  105,  105,  105,  105,   96,
      105,  105,  105,  105,  105,  105,    7,  105,   32,  105,
      105,  100,  105,  105,   45,  105,   27,  105,  105,  105,
      105,  105,  105,  105,   12,  105,   99,  105,  105,  105,

      105,  105,  105,   18,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,   91,  118,   52,  101,  105,
      105,   56,   48,  105,  105,  105,   31,  105,  105,  105,
      105,  105,  105,    9,  105,   16,   50,  105,   15,   13,
      105,  105,  105,   95,  105,  105,  105,   97,  105,    6,
      105,  105,  105,   30,  105,   25,  105,  105,  105,   51,
      105,  105,   10,   55,  105,  105,  105,    8,  105,   26,
       49,   28,  105,   40,   20,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,   33,   24,  105,   37,  105,
       34,  105,   21,  105,   53,  105,   39,  105,   42,  105,

       36,  105,  103,   46,   23,   54,  105,   14,   57,   38,
      105,   47,   98,   41,  105,   22,  104,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   27,   28,   29,   30,
       31,   31,   32,   31,   31,   33,   31,   34,   35,   31,
       31,   36,   31,   31,   37,   31,   31,   38,   31,   31,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   31,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[73] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1,    2,    4,    4,    4,    4,    4,    4,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[324] =
    {   0,
        0,    0,   70,   71,  225,  990,  217,  990,  185,   70,
      990,  990,  990,  165,  990,  990,  990,  990,  990,  167,
      990,   63,   60,   70,  163,  990,   78,  150,   61,   72,
       84,   92,   94,   96,  130,  990,  990,  100,  102,  109,
      106,  114,  121,  119,  117,  123,  126,  158,  128,  164,
      130,  132,  169,  178,  182,  180,  184,  188,  990,   98,
      990,  990,  990,  990,  144,  124,  154,  990,   77,  990,
      208,  125,  219,  990,  990,  990,  990,  201,  235,    0,
      231,  990,   98,  990,  990,   83,  990,  990,  990,  195,
      203,  242,  253,  255,  247,  990,  265,  271,  273,  275,

      277,  280,  283,  285,  287,  289,  291,  293,  300,  295,
      302,  306,  309,  314,  316,  321,  323,  325,  329,  338,
      342,  344,  346,  349,  353,  355,  361,  363,  366,  373,
      377,  379,  381,  386,  383,  389,  391,  393,  396,  403,
      408,  410,  415,  417,  425,  433,   35,  990,   67,   90,
      104,  451,  990,   83,  438,    0,  446,  430,  990,  990,
      452,  460,  464,  456,  468,  473,  475,  479,  482,  484,
      486,  490,  498,  503,  509,  512,  514,  516,  520,  522,
      525,  528,  531,  533,  535,  539,  542,  544,  548,  553,
      550,  556,  560,  562,  564,  566,  568,  570,  576,  580,

      583,  585,  589,  600,  602,  606,  608,  612,  614,  616,
      618,  620,  626,  630,  632,  990,  990,  636,  638,  644,
      648,  656,  660,  662,  664,  669,  666,  671,  673,  675,
      677,  679,  681,  684,  686,  689,  691,  693,  695,  697,
      699,  709,  712,  716,  718,  722,  726,  731,  733,  735,
      737,  739,  741,  748,  756,  758,  760,  763,  769,  771,
      773,  777,  779,  781,  783,  785,  787,  789,  791,  795,
      800,  802,  807,  809,  815,  817,  822,  824,  827,  830,
      832,  834,  836,  838,  844,  841,  846,  848,  852,  854,
      856,  858,  863,  865,  868,  870,  877,  879,  883,  887,

      889,  891,  893,  895,  899,  903,  905,  907,  910,  912,
      917,  919,  922,  924,  926,  928,  930,  990,  974,  978,
      982,  985,   74
    } ;

static yyconst short int yy_def[324] =
    {   0,
      318,    1,  319,  319,  318,  318,  318,  318,  318,  320,
      318,  318,  318,  321,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  322,
      322,  322,  322,  322,  318,  318,  318,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  320,  318,
      320,  318,  318,  318,  318,  318,  318,  318,  318,  323,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  322,
      322,  322,  322,  322,  322,  318,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  318,  318,  318,  320,
      320,  320,  318,  318,  318,  323,  318,  318,  318,  318,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  318,  318,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,    0,  318,  318,
      318,  318,  318
    } ;

static yyconst short int yy_nxt[1063] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   31,   31,   32,
       31,   31,   31,   33,   34,   31,   31,   31,   35,    6,
       36,   37,   31,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   31,   47,   48,   49,   50,   51,   52,   31,
       53,   54,   55,   56,   57,   58,   31,   31,   59,   60,
       61,   62,   64,   64,   70,   75,   78,  156,   79,   79,
       76,   70,   65,   65,   88,   89,   78,   77,   79,   79,
       91,   91,  153,   83,   70,   84,  217,   80,   66,   66,

       85,   86,   91,   91,  216,   92,  160,   81,   70,   71,
       91,   91,   91,   91,   91,   91,   71,   81,   91,   91,
       91,   91,  159,   93,   91,   91,   80,   91,   91,   71,
       94,   95,   91,   91,  153,   91,   91,   91,   91,   91,
       91,   91,   91,   71,   91,   91,   91,   91,   91,   91,
       91,   91,  101,  103,   97,   67,   98,  104,  149,  102,
      116,  148,  100,  105,  109,   99,  115,  147,  106,  107,
       96,  117,  110,  119,   87,  111,   91,   91,  112,  118,
      108,  113,   91,   91,  114,  123,   82,   91,   91,  129,
      126,   74,  130,  127,  128,  131,   91,   91,   91,   91,

       91,   91,   91,   91,   73,  120,   91,   91,   68,  121,
      124,  125,  150,   91,   91,  122,  132,  151,   67,  155,
      155,   91,   91,   72,  318,  134,  151,  133,  154,  135,
      145,  136,  140,  141,  318,  137,  143,   72,  146,  318,
      138,  144,  142,  139,  157,  318,  157,  152,   81,  158,
      158,   78,  151,   79,   79,  318,  151,  318,   72,  318,
       91,   91,  318,   72,  151,   91,   91,   72,  151,  161,
      151,   91,   91,   91,   91,   72,  318,  151,  318,   72,
      318,   72,   81,   91,   91,  162,  318,  163,   72,   91,
       91,   91,   91,   91,   91,   91,   91,  318,   91,   91,

      157,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,  318,  166,  165,   91,   91,
       91,   91,  167,  169,   91,   91,  318,   91,   91,  318,
      164,  171,   91,   91,   91,   91,  170,  318,  168,   91,
       91,   91,   91,   91,   91,  318,  172,   91,   91,  174,
      173,  177,  180,  318,  176,  175,   91,   91,  318,  178,
       91,   91,   91,   91,   91,   91,  179,   91,   91,  318,
      181,   91,   91,   91,   91,  183,  186,  318,  182,   91,
       91,   91,   91,  184,   91,   91,  318,  185,  318,  189,
      318,   91,   91,  318,  187,   91,   91,   91,   91,   91,

       91,   91,   91,  188,   91,   91,  190,   91,   91,   91,
       91,   91,   91,  318,   91,   91,  318,  193,  318,  191,
      194,   91,   91,  192,  198,  195,   91,   91,   91,   91,
      196,  318,  202,   91,   91,   91,   91,  199,  200,  197,
      203,  318,  201,   91,   91,  318,  204,  206,  158,  158,
      207,   91,   91,  205,  318,  150,  155,  155,  318,  157,
      151,  157,  318,  208,  158,  158,  210,  318,  213,  151,
       91,   91,  318,  209,   91,   91,  211,  212,   91,   91,
      318,  214,   91,   91,  215,   81,   91,   91,  218,  318,
      152,   91,   91,   91,   91,  151,  219,   91,   91,  151,

       91,   91,   91,   91,   91,   91,  318,  151,   91,   91,
      318,  151,  318,  151,  318,  157,   91,   91,  221,  318,
      151,   91,   91,  318,  220,  318,  222,   91,   91,  224,
       91,   91,   91,   91,   91,   91,  318,  225,   91,   91,
       91,   91,  223,   91,   91,  227,   91,   91,  226,   91,
       91,   91,   91,   91,   91,  318,  229,   91,   91,  231,
       91,   91,   91,   91,  318,  228,   91,   91,   91,   91,
      233,   91,   91,  230,   91,   91,  318,  232,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
      318,  238,  318,  234,   91,   91,  235,  236,   91,   91,

      239,   91,   91,   91,   91,  318,  237,   91,   91,  318,
      243,  244,  240,  318,  241,  318,  242,  245,   91,   91,
       91,   91,  318,  246,   91,   91,   91,   91,  318,  248,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
      318,  249,  318,  247,   91,   91,  318,  250,   91,   91,
       91,   91,  318,  251,   91,   91,   91,   91,  318,  255,
      318,  256,   91,   91,  254,  252,   91,   91,  253,  258,
      318,  259,  260,  257,   91,   91,  318,  261,   91,   91,
       91,   91,   91,   91,   91,   91,  262,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       91,  264,   91,   91,   91,   91,  263,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,  318,
      266,  318,  270,  267,  318,  265,  272,   91,   91,  318,
       91,   91,  318,  269,   91,   91,   91,   91,  268,  271,
       91,   91,  318,  273,   91,   91,  318,  275,  274,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,  318,  276,  278,  318,  280,   91,   91,  318,  279,
      318,  277,  318,  281,   91,   91,   91,   91,   91,   91,
      282,   91,   91,  318,  284,  318,  285,   91,   91,   91,
       91,   91,   91,  283,  318,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,  318,  288,   91,   91,  318,  287,  286,   91,   91,
       91,   91,  318,  289,  291,   91,   91,   91,   91,  318,
      294,  318,  293,   91,   91,   91,   91,  292,  318,  290,
       91,   91,   91,   91,  318,   91,   91,  295,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,  296,   91,
       91,  318,   91,   91,   91,   91,   91,   91,  318,  298,
       91,   91,   91,   91,   91,   91,   91,   91,  318,  297,
      303,   91,   91,   91,   91,  304,   91,   91,   91,   91,
      299,  300,  301,  302,  306,   91,   91,   91,   91,  318,

      305,   91,   91,  318,  307,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,  318,  308,   91,   91,  318,
      309,   91,   91,   91,   91,   91,   91,  311,   91,   91,
       91,   91,  310,  318,  313,   91,   91,   91,   91,  312,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
      318,  318,  315,  314,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  317,  316,   63,   63,   63,   63,   69,   69,
       69,   69,   72,   72,  318,   72,   90,  318,   90,    5,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yyconst short int yy_chk[1063] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,   10,   22,   23,  323,   23,   23,
       22,   69,    3,    4,   29,   29,   24,   22,   24,   24,
       30,   30,  154,   27,  150,   27,  149,   23,    3,    4,

       27,   27,   31,   31,  147,   30,   86,   23,  151,   10,
       32,   32,   33,   33,   34,   34,   69,   24,   38,   38,
       39,   39,   83,   32,   41,   41,   23,   40,   40,  150,
       33,   34,   42,   42,   72,   45,   45,   44,   44,   43,
       43,   46,   46,  151,   47,   47,   49,   49,   51,   51,
       52,   52,   40,   41,   38,   67,   38,   41,   66,   40,
       45,   65,   39,   41,   43,   38,   44,   60,   42,   42,
       35,   46,   43,   47,   28,   43,   48,   48,   43,   46,
       42,   43,   50,   50,   43,   49,   25,   53,   53,   52,
       51,   20,   52,   51,   51,   52,   54,   54,   56,   56,

       55,   55,   57,   57,   14,   48,   58,   58,    9,   48,
       50,   50,   71,   90,   90,   48,   53,   71,    7,   78,
       78,   91,   91,   73,    5,   54,   71,   53,   73,   54,
       58,   54,   55,   55,    0,   54,   56,   73,   58,    0,
       54,   57,   55,   54,   81,    0,   81,   71,   78,   81,
       81,   79,   71,   79,   79,    0,   71,    0,   73,    0,
       92,   92,    0,   73,   71,   95,   95,   73,   71,   92,
       71,   93,   93,   94,   94,   73,    0,   71,    0,   73,
        0,   73,   79,   97,   97,   93,    0,   94,   73,   98,
       98,   99,   99,  100,  100,  101,  101,    0,  102,  102,

       81,  103,  103,  104,  104,  105,  105,  106,  106,  107,
      107,  108,  108,  110,  110,    0,   99,   98,  109,  109,
      111,  111,  100,  102,  112,  112,    0,  113,  113,    0,
       97,  103,  114,  114,  115,  115,  102,    0,  101,  116,
      116,  117,  117,  118,  118,    0,  104,  119,  119,  107,
      106,  110,  113,    0,  109,  108,  120,  120,    0,  111,
      121,  121,  122,  122,  123,  123,  112,  124,  124,    0,
      114,  125,  125,  126,  126,  116,  119,    0,  115,  127,
      127,  128,  128,  118,  129,  129,    0,  118,    0,  122,
        0,  130,  130,    0,  120,  131,  131,  132,  132,  133,

      133,  135,  135,  121,  134,  134,  123,  136,  136,  137,
      137,  138,  138,    0,  139,  139,    0,  129,    0,  125,
      130,  140,  140,  127,  132,  130,  141,  141,  142,  142,
      130,    0,  135,  143,  143,  144,  144,  132,  132,  131,
      136,    0,  134,  145,  145,    0,  137,  139,  158,  158,
      140,  146,  146,  138,    0,  152,  155,  155,    0,  157,
      152,  157,    0,  141,  157,  157,  143,    0,  144,  152,
      161,  161,    0,  142,  164,  164,  143,  143,  162,  162,
        0,  145,  163,  163,  146,  155,  165,  165,  162,    0,
      152,  166,  166,  167,  167,  152,  163,  168,  168,  152,

      169,  169,  170,  170,  171,  171,    0,  152,  172,  172,
        0,  152,    0,  152,    0,  157,  173,  173,  167,    0,
      152,  174,  174,    0,  166,    0,  168,  175,  175,  171,
      176,  176,  177,  177,  178,  178,    0,  171,  179,  179,
      180,  180,  169,  181,  181,  173,  182,  182,  172,  183,
      183,  184,  184,  185,  185,    0,  175,  186,  186,  178,
      187,  187,  188,  188,    0,  174,  189,  189,  191,  191,
      181,  190,  190,  176,  192,  192,    0,  180,  193,  193,
      194,  194,  195,  195,  196,  196,  197,  197,  198,  198,
        0,  189,    0,  183,  199,  199,  184,  186,  200,  200,

      190,  201,  201,  202,  202,    0,  188,  203,  203,    0,
      194,  196,  191,    0,  192,    0,  193,  198,  204,  204,
      205,  205,    0,  199,  206,  206,  207,  207,    0,  201,
      208,  208,  209,  209,  210,  210,  211,  211,  212,  212,
        0,  202,    0,  200,  213,  213,    0,  203,  214,  214,
      215,  215,    0,  205,  218,  218,  219,  219,    0,  208,
        0,  209,  220,  220,  207,  205,  221,  221,  206,  211,
        0,  212,  213,  210,  222,  222,    0,  214,  223,  223,
      224,  224,  225,  225,  227,  227,  215,  226,  226,  228,
      228,  229,  229,  230,  230,  231,  231,  232,  232,  233,

      233,  221,  234,  234,  235,  235,  220,  236,  236,  237,
      237,  238,  238,  239,  239,  240,  240,  241,  241,    0,
      225,    0,  230,  226,    0,  224,  232,  242,  242,    0,
      243,  243,    0,  229,  244,  244,  245,  245,  228,  231,
      246,  246,    0,  233,  247,  247,    0,  238,  235,  248,
      248,  249,  249,  250,  250,  251,  251,  252,  252,  253,
      253,    0,  241,  243,    0,  246,  254,  254,    0,  245,
        0,  242,    0,  247,  255,  255,  256,  256,  257,  257,
      249,  258,  258,    0,  252,    0,  253,  259,  259,  260,
      260,  261,  261,  251,    0,  262,  262,  263,  263,  264,

      264,  265,  265,  266,  266,  267,  267,  268,  268,  269,
      269,    0,  258,  270,  270,    0,  257,  255,  271,  271,
      272,  272,    0,  259,  262,  273,  273,  274,  274,    0,
      267,    0,  266,  275,  275,  276,  276,  265,    0,  261,
      277,  277,  278,  278,    0,  279,  279,  269,  280,  280,
      281,  281,  282,  282,  283,  283,  284,  284,  273,  286,
      286,    0,  285,  285,  287,  287,  288,  288,    0,  277,
      289,  289,  290,  290,  291,  291,  292,  292,    0,  276,
      282,  293,  293,  294,  294,  283,  295,  295,  296,  296,
      278,  279,  280,  281,  285,  297,  297,  298,  298,    0,

      284,  299,  299,    0,  288,  300,  300,  301,  301,  302,
      302,  303,  303,  304,  304,    0,  290,  305,  305,    0,
      292,  306,  306,  307,  307,  308,  308,  296,  309,  309,
      310,  310,  294,    0,  300,  311,  311,  312,  312,  298,
      313,  313,  314,  314,  315,  315,  316,  316,  317,  317,
        0,    0,  307,  302,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  315,  311,  319,  319,  319,  319,  320,  320,
      320,  320,  321,  321,    0,  321,  322,    0,  322,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "MSV.l"
#define INITIAL 0
#line 2 "MSV.l"
#include "function.h"
#include <string.h> // strcpy, strncpy
#include <math.h>
#include <io.h>     // isatty.h>
#include "MyMap.h"
#include "SyntaxNode.h"




extern CMAP g_StructNameMap;
int lineno=1;

// For some reason isatty is called _isatty in Visual C++
#ifdef MSVC
#define isatty _isatty
#endif

// Forward declarations for include files
class CSyntaxNode;
class Symbol;
class SymbolTable;

// Make sure our variables get created
#define  _LEX_CPP_
//#include "lex.h"
//#include "lexSymbol.h"
#include "parse.cpp.h"

// The yywrap and error functions are declared by the caller
extern "C" int yywrap();
extern void error( char *cFormat, ... );
extern 

void DeleteSingleLineComment (void);
void passStringConstant (void);

#define comment 1

/*
\b 退格
\f 走纸换页
\n 换行
\r 回车
\t 横向跳格 (Ctrl-I)
\' 单引号
\" 双引号
\\反斜杠
*/
#line 755 "lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 "MSV.l"


#line 905 "lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 319 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 990 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 70 "MSV.l"
BEGIN comment;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "MSV.l"
{return AND;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "MSV.l"
{return OR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "MSV.l"
{return BOOL_AND;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "MSV.l"
{return BOOL_OR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "MSV.l"
{return SKIP;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "MSV.l"
{return FINAL;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "MSV.l"
{return EMPTY;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "MSV.l"
{return HALT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "MSV.l"
{return AWAIT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "MSV.l"
{return PARALLEL;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "MSV.l"
{return PROJECTION;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "MSV.l"
{return NEXT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "MSV.l"
{return W_NEXT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "MSV.l"
{return MORE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "MSV.l"
{return KEEP;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "MSV.l"
{return ALWAYS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "MSV.l"
{return SOMETIMES;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "MSV.l"
{return COLON;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "MSV.l"
{return EXIST;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "MSV.l"
{return DEFINE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "MSV.l"
{return FUNCTION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "MSV.l"
{return STRUCT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "MSV.l"
{return UNION;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "MSV.l"
{return MY_TRUE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "MSV.l"
{return MY_FALSE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "MSV.l"
{return LENGTH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "MSV.l"
{return FRAME;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "MSV.l"
{return IF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "MSV.l"
{return THEN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "MSV.l"
{return ELSE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "MSV.l"
{return FOR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "MSV.l"
{return TIMES;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "MSV.l"
{return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "MSV.l"
{return DO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "MSV.l"
{return REPEAT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "MSV.l"
{return UNTIL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "MSV.l"
{return PREFIX;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 114 "MSV.l"
{return CHOP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 115 "MSV.l"
{return ADDRESS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 116 "MSV.l"
{return INTDECLARATION;}//  added by Jane 2012-05-21
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 117 "MSV.l"
{return STRDECLARATION;}//STRVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "MSV.l"
{return POINTERDECLARATION;}//POINTER  added by Jane 2012-05-21
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "MSV.l"
{return CHARDECLARATION;}//CHARVARIABLE  added by Jane 2012-05-21 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "MSV.l"
{return FLOATDECLARATION;}//FLOATVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 121 "MSV.l"
{return LISTDECLARATION;}//LISTVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "MSV.l"
{return VOIDDECLARATION;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 125 "MSV.l"
{return FILEDECLARATION;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 126 "MSV.l"
{return EXTERN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 127 "MSV.l"
{return SWITCH;}//add by yubin 2015-3-23
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "MSV.l"
{return BREAK;}//add by yubin 2015-3-23
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 129 "MSV.l"
{return CASE;}//add by yubin 2015-3-23
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 130 "MSV.l"
{return DEFAULT;}//add by yubin 2015-3-23
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "MSV.l"
{return DOT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "MSV.l"
{return EQ;}     //比较相等符号 “=”
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "MSV.l"
{return ASS_P;}   //赋值符号已修改为“<==”
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 136 "MSV.l"
{return ASS_N;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 138 "MSV.l"
{return LT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 139 "MSV.l"
{return GT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 140 "MSV.l"
{return LE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 141 "MSV.l"
{return GE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 142 "MSV.l"
{return NE;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 143 "MSV.l"
{return NEGATION;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 144 "MSV.l"
{return PBEGIN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 145 "MSV.l"
{return PEND;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 147 "MSV.l"
{return ADD;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 148 "MSV.l"
{return SUB;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 149 "MSV.l"
{return MUL;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 150 "MSV.l"
{return DIV;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 151 "MSV.l"
{return MOD;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 152 "MSV.l"
{return CON;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 153 "MSV.l"
{return LST;}//左移 left shift
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 154 "MSV.l"
{return RST;}//右移 right shift
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 155 "MSV.l"
{return BNE;}//按位非 bit negation
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "MSV.l"
{return PROPIMPLY;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 158 "MSV.l"
{return IMPLY;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 159 "MSV.l"
{return IFF;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 161 "MSV.l"
{return OPEN_PAR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 162 "MSV.l"
{return CLOSE_PAR;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 163 "MSV.l"
{return OPEN_MPAR;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 164 "MSV.l"
{return CLOSE_MPAR;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 165 "MSV.l"
{return OPEN_BPAR;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 166 "MSV.l"
{return CLOSE_BPAR;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 167 "MSV.l"
{return COMMA;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 168 "MSV.l"
{return CHOPSTAR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 171 "MSV.l"
{return OVER;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 172 "MSV.l"
{return CYLINDER;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 173 "MSV.l"
{return OVEREP;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 175 "MSV.l"
{return	INTER_OR;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 176 "MSV.l"
{return NON_DETERMINED;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 178 "MSV.l"
{return PROCESS;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 179 "MSV.l"
{return CHANNEL;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 180 "MSV.l"
{return SEND;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 181 "MSV.l"
{return RECEIVE;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 182 "MSV.l"
{return PUT;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 183 "MSV.l"
{return GET;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 185 "MSV.l"
{return POINTERNULL;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 186 "MSV.l"
{return ARRAY;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 188 "MSV.l"
{return SIGNED;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 189 "MSV.l"
{return UNSIGNED;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 193 "MSV.l"
{
			   yylval.cString=new char[strlen(yytext)+1];
			   strcpy(yylval.cString,yytext);
               
			   if(!g_StructNameMap.find(yytext))
			   {
			       return ID;
			   }
			   else
			   {
                   return STRUCT_TYPE;
			   }
		}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 206 "MSV.l"
{    
               yylval.nInteger=atoi(yytext);
               return INTLITERAL;
		 }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 210 "MSV.l"
{    
               int decValue;//int，保存16进制对应的十进制数
			   sscanf(yytext,"%x",&decValue);//将16进制字符串转成10进制数
			   yylval.nInteger=decValue;//将10进制数赋给yytext
               return INTLITERAL;
			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 216 "MSV.l"
{
               char* result=NULL;
			   result=strtok(yytext, "e");
			   int iVal;
			   float fVal;
			   sscanf(result, "%f", &fVal);
			   while(result!=NULL)
			   {
			      sscanf(result, "%d", &iVal);
				  result = strtok(NULL, "e");
				}

               yylval.floatval = fVal*pow(10, iVal); 
			   return FLOATLITERAL;
			}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 231 "MSV.l"
{
               passStringConstant ();
			   return STRLITERAL;
         }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 236 "MSV.l"
{		
				yylval. floatval = atof(yytext); 
				return FLOATLITERAL; 
		 }//Added by Jane 2012-05-21 
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 240 "MSV.l"
{//modified by yubin 2014/2/25，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
				if(yytext[1]!='\\')
				{
					yylval.character=yytext[1];
					return CHARLITERAL;
				}
				else if(yytext[2]=='n')
				{
					yylval.character='\n';
					return CHARLITERAL;
				}
				else if(yytext[2]=='b')
				{
					yylval.character='\b';
					return CHARLITERAL;
				}
				else if(yytext[2]=='f')
				{
					yylval.character='\f';
					return CHARLITERAL;
				}
				else if(yytext[2]=='r')
				{
					yylval.character='\r';
					return CHARLITERAL;
				}
				else if(yytext[2]=='t')
				{
					yylval.character='\t';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\'')
				{
					yylval.character='\'';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\"')
				{
					yylval.character='\"';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\\')
				{
					yylval.character='\\';
					return CHARLITERAL;
				}
				else if(yytext[2]=='0')
				{
					yylval.character='\0';
					return CHARLITERAL;
				}
		}   //2013-4-22 add by YY[fixed]
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 295 "MSV.l"
{DeleteSingleLineComment();}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 296 "MSV.l"
{++lineno;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 297 "MSV.l"
{}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 298 "MSV.l"
{return ERROR_TOKEN;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 300 "MSV.l"
{}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 301 "MSV.l"
{++lineno;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 302 "MSV.l"
{error("EOF in comment");}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 303 "MSV.l"
{BEGIN 0;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 305 "MSV.l"
ECHO;
	YY_BREAK
#line 1679 "lex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 319 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 319 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 318);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 305 "MSV.l"


void DeleteSingleLineComment(void)
{
    register int c;

	while((c=yyinput()) != '\n' && c!=EOF)
	{
	    // do nothing
    }
	++lineno;
}

void passStringConstant (void)
{//modified by yubin 2014/2/25，处理char*字符串中的转义字符，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
	int l = ( strlen( yytext ) - 2 );
	yylval.cString = new char[l+1];
	strncpy( yylval.cString, &yytext[1], l );
	int i;
	int j=0;//j用来记录转义字符的个数
	for(i=0;i+j<l;i=i+1)
	{
		if(yylval.cString[i+j]!='\\')
		{
			yylval.cString[i]=yylval.cString[i+j];
		}
		else if(yylval.cString[i+j+1]=='n')
		{
			yylval.cString[i]='\n';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='b')
		{
			yylval.cString[i]='\b';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='f')
		{
			yylval.cString[i]='\f';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='r')
		{
			yylval.cString[i]='\r';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='t')
		{
			yylval.cString[i]='\t';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\'')
		{
			yylval.cString[i]='\'';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\"')
		{
			yylval.cString[i]='\"';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\\')
		{
			yylval.cString[i]='\\';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='0')
		{
			yylval.cString[i]='\0';
			j=j+1;
		}
		else//是转义字符，但是不是上面的一些转义字符，暂时什么也不做
		{
		
		}	
	}
	yylval.cString[i] = '\0';
}